# syntax = docker/dockerfile:1

FROM zhongruoyu/sandbox:jammy

COPY --chmod=755 <<EOF /usr/local/bin/docker-entrypoint.sh
#!/bin/bash
service ssh start
exec "$@"
EOF
ENTRYPOINT [ "docker-entrypoint.sh" ]
CMD [ "bash" ]
EXPOSE 22

RUN <<EOF
groupadd -g 1000 ruoyu
useradd -d /home/ruoyu -g ruoyu -m -s /usr/bin/zsh -u 1000 ruoyu
echo "ruoyu ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/ruoyu
EOF
VOLUME [ "/home/ruoyu" ]
