name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 1 * *"

jobs:
  docker:
    strategy:
      matrix:
        target:
          - tags: zhongruoyu/workbench:latest,zhongruoyu/workbench:ubuntu,zhongruoyu/workbench:jammy
            file: jammy.Dockerfile
            platforms: linux/amd64,linux/arm64
          - tags: zhongruoyu/workbench:focal
            file: focal.Dockerfile
            platforms: linux/amd64,linux/arm64
          - tags: zhongruoyu/workbench:fedora
            file: fedora.Dockerfile
            platforms: linux/amd64,linux/arm64
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.target.file }}
          platforms: ${{ matrix.target.platforms }}
          push: true
          tags: ${{ matrix.target.tags }}
