name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        target:
          - tags: zhongruoyu/workbench:noble,zhongruoyu/workbench:ubuntu,zhongruoyu/workbench:latest
            platforms: linux/amd64,linux/arm64
            file: ubuntu.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:noble
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:plucky
            platforms: linux/amd64,linux/arm64
            file: ubuntu.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:plucky
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:jammy
            platforms: linux/amd64,linux/arm64
            file: ubuntu.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:jammy
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:focal
            platforms: linux/amd64,linux/arm64
            file: ubuntu.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:focal
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:debian,zhongruoyu/workbench:trixie
            platforms: linux/amd64,linux/arm64
            file: debian.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:trixie
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:bookworm
            platforms: linux/amd64,linux/arm64
            file: debian.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:bookworm
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:bullseye
            platforms: linux/amd64,linux/arm64
            file: debian.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:bullseye
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:fedora
            platforms: linux/amd64,linux/arm64
            file: fedora.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:fedora
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:rockylinux,zhongruoyu/workbench:rockylinux-10
            platforms: linux/amd64,linux/arm64
            file: rockylinux.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:rockylinux-10
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:rockylinux-9
            platforms: linux/amd64,linux/arm64
            file: rockylinux.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:rockylinux-9
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:rockylinux-8
            platforms: linux/amd64,linux/arm64
            file: rockylinux.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:rockylinux-8
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:almalinux,zhongruoyu/workbench:almalinux-10
            platforms: linux/amd64,linux/arm64
            file: almalinux.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:almalinux-10
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:almalinux-9
            platforms: linux/amd64,linux/arm64
            file: almalinux.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:almalinux-9
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:almalinux-8
            platforms: linux/amd64,linux/arm64
            file: almalinux.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:almalinux-8
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:opensuse,zhongruoyu/workbench:opensuse-tumbleweed
            platforms: linux/amd64
            file: opensuse.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:opensuse-tumbleweed
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:opensuse-leap,zhongruoyu/workbench:opensuse-leap-15
            platforms: linux/amd64
            file: opensuse.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:opensuse-leap-15
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:archlinux
            platforms: linux/amd64
            file: archlinux.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:archlinux
              USERNAME=ruoyu
          - tags: zhongruoyu/workbench:alpine
            platforms: linux/amd64,linux/arm64
            file: alpine.Dockerfile
            build-args: |
              BASE_IMAGE=zhongruoyu/sandbox:alpine
              USERNAME=ruoyu
    name: ${{ matrix.target.tags }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: ${{ matrix.target.tags }}
          platforms: ${{ matrix.target.platforms }}
          file: ${{ matrix.target.file }}
          build-args: ${{ matrix.target.build-args }}
          push: true
