name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docker:
    strategy:
      matrix:
        target:
          - build-args: |
              IMAGE_TAG=jammy
            file: ubuntu.Dockerfile
            platforms: |
              linux/amd64
              linux/arm64
            tags: |
              zhongruoyu/workbench:latest
              zhongruoyu/workbench:ubuntu
              zhongruoyu/workbench:jammy
          - build-args: |
              IMAGE_TAG=focal
            file: ubuntu.Dockerfile
            platforms: |
              linux/amd64
              linux/arm64
            tags: |
              zhongruoyu/workbench:focal
          - build-args: |
              IMAGE_TAG=bullseye
            file: debian.Dockerfile
            platforms: |
              linux/amd64
              linux/arm64
            tags: |
              zhongruoyu/workbench:debian
              zhongruoyu/workbench:bullseye
          - build-args: |
              IMAGE_TAG=fedora
            file: fedora.Dockerfile
            platforms: |
              linux/amd64
              linux/arm64
            tags: |
              zhongruoyu/workbench:fedora
          - build-args: |
              IMAGE_TAG=archlinux
            file: archlinux.Dockerfile
            platforms: |
              linux/amd64
            tags: |
              zhongruoyu/workbench:archlinux
          - build-args: |
              IMAGE_TAG=rockylinux
            file: rockylinux.Dockerfile
            platforms: |
              linux/amd64
              linux/arm64
            tags: |
              zhongruoyu/workbench:rockylinux
          - build-args: |
              IMAGE_TAG=alpine
            file: alpine.Dockerfile
            platforms: |
              linux/amd64
              linux/arm64
            tags: |
              zhongruoyu/workbench:alpine
          - build-args: |
              IMAGE_TAG=clearlinux
            file: clearlinux.Dockerfile
            platforms: |
              linux/amd64
            tags: |
              zhongruoyu/workbench:clearlinux
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          build-args: ${{ matrix.target.build-args }}
          file: ${{ matrix.target.file }}
          platforms: ${{ matrix.target.platforms }}
          push: true
          tags: ${{ matrix.target.tags }}
