name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  USERNAME: ruoyu

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: trixie
            file: debian.Dockerfile
            arch: x86_64
          - tag: trixie
            file: debian.Dockerfile
            arch: aarch64
          - tag: bookworm
            file: debian.Dockerfile
            arch: x86_64
          - tag: bookworm
            file: debian.Dockerfile
            arch: aarch64
          - tag: bullseye
            file: debian.Dockerfile
            arch: x86_64
          - tag: bullseye
            file: debian.Dockerfile
            arch: aarch64
          - tag: sid
            file: debian.Dockerfile
            arch: x86_64
          - tag: sid
            file: debian.Dockerfile
            arch: aarch64
          - tag: noble
            file: ubuntu.Dockerfile
            arch: x86_64
          - tag: noble
            file: ubuntu.Dockerfile
            arch: aarch64
          - tag: jammy
            file: ubuntu.Dockerfile
            arch: x86_64
          - tag: jammy
            file: ubuntu.Dockerfile
            arch: aarch64
          - tag: focal
            file: ubuntu.Dockerfile
            arch: x86_64
          - tag: focal
            file: ubuntu.Dockerfile
            arch: aarch64
          - tag: plucky
            file: ubuntu.Dockerfile
            arch: x86_64
          - tag: plucky
            file: ubuntu.Dockerfile
            arch: aarch64
          - tag: fedora
            file: fedora.Dockerfile
            arch: x86_64
          - tag: fedora
            file: fedora.Dockerfile
            arch: aarch64
          - tag: almalinux-10
            file: almalinux.Dockerfile
            arch: x86_64
          - tag: almalinux-10
            file: almalinux.Dockerfile
            arch: aarch64
          - tag: almalinux-9
            file: almalinux.Dockerfile
            arch: x86_64
          - tag: almalinux-9
            file: almalinux.Dockerfile
            arch: aarch64
          - tag: almalinux-8
            file: almalinux.Dockerfile
            arch: x86_64
          - tag: almalinux-8
            file: almalinux.Dockerfile
            arch: aarch64
          - tag: rockylinux-10
            file: rockylinux.Dockerfile
            arch: x86_64
          - tag: rockylinux-10
            file: rockylinux.Dockerfile
            arch: aarch64
          - tag: rockylinux-9
            file: rockylinux.Dockerfile
            arch: x86_64
          - tag: rockylinux-9
            file: rockylinux.Dockerfile
            arch: aarch64
          - tag: rockylinux-8
            file: rockylinux.Dockerfile
            arch: x86_64
          - tag: rockylinux-8
            file: rockylinux.Dockerfile
            arch: aarch64
          - tag: archlinux
            file: archlinux.Dockerfile
            arch: x86_64
          - tag: opensuse-tumbleweed
            file: opensuse.Dockerfile
            arch: x86_64
          - tag: opensuse-tumbleweed
            file: opensuse.Dockerfile
            arch: aarch64
          - tag: opensuse-leap-15
            file: opensuse.Dockerfile
            arch: x86_64
          - tag: opensuse-leap-15
            file: opensuse.Dockerfile
            arch: aarch64
          - tag: alpine
            file: alpine.Dockerfile
            arch: x86_64
          - tag: alpine
            file: alpine.Dockerfile
            arch: aarch64
    name: Build ${{ matrix.tag }} (${{ matrix.arch }})
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.file }}
          platforms: linux/${{ matrix.arch }}
          build-args: |
            BASE_IMAGE=zhongruoyu/sandbox:${{ matrix.tag }}
            USERNAME=${{ env.USERNAME }}
          outputs: type=image,name=zhongruoyu/workbench,name-canonical=true,push=true,push-by-digest=true
      - name: Export digest
        run: |
          mkdir -p "$RUNNER_TEMP"/digests
          echo "${DIGEST#sha256:}" > "$RUNNER_TEMP"/digests/"$TAG-$ARCH"
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          TAG: ${{ matrix.tag }}
          ARCH: ${{ matrix.arch }}
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.tag }}-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*

  merge:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - primary-tag: trixie
            tags: trixie debian-13 debian latest
          - primary-tag: bookworm
            tags: bookworm debian-12
          - primary-tag: bullseye
            tags: bullseye debian-11
          - primary-tag: sid
            tags: sid debian-unstable
          - primary-tag: noble
            tags: noble ubuntu-24.04 ubuntu
          - primary-tag: jammy
            tags: jammy ubuntu-22.04
          - primary-tag: focal
            tags: focal ubuntu-20.04
          - primary-tag: plucky
            tags: plucky ubuntu-25.04
          - primary-tag: fedora
            tags: fedora
          - primary-tag: almalinux-10
            tags: almalinux-10 almalinux
          - primary-tag: almalinux-9
            tags: almalinux-9
          - primary-tag: almalinux-8
            tags: almalinux-8
          - primary-tag: rockylinux-10
            tags: rockylinux-10 rockylinux
          - primary-tag: rockylinux-9
            tags: rockylinux-9
          - primary-tag: rockylinux-8
            tags: rockylinux-8
          - primary-tag: archlinux
            tags: archlinux
          - primary-tag: opensuse-tumbleweed
            tags: opensuse-tumbleweed opensuse
          - primary-tag: opensuse-leap-15
            tags: opensuse-leap-15 opensuse-leap
          - primary-tag: alpine
            tags: alpine
    name: Merge ${{ matrix.primary-tag }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download digests
        uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ matrix.primary-tag }}-*
          merge-multiple: true
      - name: Create manifest list and push
        run: |
          tags=()
          for tag in $TAGS; do
            tags+=("--tag=zhongruoyu/workbench:$tag")
          done

          images=()
          for digest in "$RUNNER_TEMP"/digests/"$PRIMARY_TAG"-*; do
            images+=("zhongruoyu/workbench@sha256:$(cat "$digest")")
          done

          docker buildx imagetools create "${tags[@]}" "${images[@]}"
        env:
          PRIMARY_TAG: ${{ matrix.primary-tag }}
          TAGS: ${{ matrix.tags }}
